# built in error
# exception , how to handle

# syntax error
# def a:
#     pass
def a():
    pass


# a = 2 +

# indentation error
# def func():
#     print('hi')
#  print('error')

# name error
# print(name)

# typr error
# print(5+'string')

# index error
# l = [1, 2, 3]
# print(l[4])

# value error
s = '5'
# s = 'abc'
print(int(s))

# attribute error
# l = [1, 2, 3]
# print(l.push())

# key error
# d = {'name': 'anik'}
# print(d['age'])
